name: rolodex
description: A Flutter widget that represents a roll of cards.
version: 0.0.1
homepage: https://github.com/aryzhov/flutter-rolodex

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
