name: rolodex
description: A Flutter widget that turns a value into an animated deck of cards.
version: 1.1.0
homepage: https://github.com/aryzhov/flutter-rolodex

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
