name: rolodex
description: A Flutter widget that animates value changes as a falling cards.
version: 1.0.0+2
homepage: https://github.com/aryzhov/flutter-rolodex

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
